### ISSUE TITLE
Adding a text/label near a node.

### ISSUE THREAD

**Issue by Avikolar** [Microsoft/automatic-graph-layout#102]
How to add text or label near nodes connecting one to other node.

**Comment by Avikolar** [comment]
i solved my issue by using this code.
                          var txtlbl =  graph.AddEdge(node1, node2);                           
                           Microsoft.Glee.Drawing.Node n1 = graph.FindNode(node2);
                           n1.Attr.Fillcolor = Microsoft.Glee.Drawing.Color.SeaGreen;                           
                           n1.Attr.Shape = Microsoft.Glee.Drawing.Shape.Box;
                           txtlbl.Attr.Label = " approved "; // adding text or label near node.

**Comment by levnach** [comment]
txtllbl above is an Edge!
