### ISSUE TITLE
UWP Port

### ISSUE THREAD

**Issue by ToddThomson** [Microsoft/automatic-graph-layout#116]
I've got the beginnings of a port of MsAGL for UWP (MsAGL library, Drawing library and GraphControl with a SimpleUwpApp). I needed a graph layout tool for UWP and Msagl seemed to fit my needs.

Are there any plans to move the MsAGL core library to Netstandard 2.0? This is likely close to what my port of MsAGL is. I'd like to contribute my code down the line!

I've uploaded my source to [github MsAGL](https://github.com/ToddThomson/MsAGL) . I'd welcome any comments.

**Comment by levnach** [comment]
Netstandard is a new thing for me. What are the benefits of porting? How much work is it?

**Comment by ToddThomson** [comment]
.Net Standard 2.0 is an API contract that will bring unification ( from a developers point of view ) to Xamarin, .NET Core and UWP. The UWP support will be coming in the Fall Update of Windows 10.  Visual Studio tooling will be coming this summer ( with v15.3 ).

The benefits are that MsAGL as a library will be consumable across all .NET implementations that implement the .NET Standard 2.0 API. 

It's not clear to me how much work is involved to update MsAGL to .NET Standard 2.0. I am concentrating my changes on Drawing and the GraphControl libraries to modernize them for UWP. I've only changed the MsAGL library so that it works with Windows 10.

**Comment by ToddThomson** [comment]
@levnach I now have a much better picture of the current MSAGL and how all the different modules come together. I didn't realize that the GDI version of the GraphViewer was feature complete vs the WPF version.

For my Windows 10 UWP work (based on the WPF GraphViewer) I will add selection, editing and zooming. This mostly involves Pointer and Gesture event handling changes.

**Comment by mkosieradzki** [comment]
Hi. I have created initial port to .NET Standard 2.0 (preview 2).
https://github.com/mkosieradzki/automatic-graph-layout - I can create a PR if you approve, @levnach 

Amount of work:
1. It's fairly similar to SILVERLIGHT (it's a bit wider API surface) - I have mostly added && !NETCORE adjacent to all !SILVERLIGHT
2. I needed to make conditional all the code references to the SolidColorBrush. (mostly in LgInteractor)

Depending on targeting preference: .NET Standard 2.0 vs .NET Standard 1.3 it's about more or less preexisting SILVERLIGHT conditions will be extended to NETCORE.

Benefits:
.NET Standard is extremely useful API surface that guarantees compatibility with multiple platforms. Basically it should be very helpful in removing most of the conditional code in the future. By targeting 
.NET Standard library would be much easier to be consumed throughout many different platforms.

Other benefits - it would be a defnitely good idea to switch to the new project system as it simplifies multi-targetting. It also simplifies nuget pacakge creation etc. My example uses the new project system.

How use my modified version:
1. Install the preview version of .NET Standard 2.0 tooling (my prototype currently targets .NET Standard 2.0, but it might be reasonable to retarget it to lower .NET Standard version) - https://www.microsoft.com/net/core/preview#windowscmd 
2. Open the solution GraphLayout.NETCore.sln

**Comment by ToddThomson** [comment]
@mkosieradzki I have been concentrating my efforts on the Graph Viewer control ( and the Drawing library it references ). I also had to update the Msagl core library to UWP, but I am waiting on the production release of VS 2017 v15.3 before porting to NetStandard 2.0. I will utilize your PR down the line.

The Msagl.Uwp.Graph library is coming along nicely. There is a working sample app. Please see the issues for the repository if you have any interest.

**Comment by ToddThomson** [comment]
The UWP port for the GraphViewer control is going well and I am aiming for an initial release in the early fall ( with the Windows Fall Update supporting .NET Standard 2 ).
I have found that the visual rendering code base ( silverlight and WPF implementations) needs more of a complete rewrite/reorg. I will be breaking the UI controls into a much simpler GraphView and GraphDesigner.
The scope for the GraphDesigner is still a bit unclear to me. It will likely be a GraphEditor control library and a Graph Designer app. 
Please let me know what you think...

**Comment by levnach** [comment]
Just a general though: I think breaking the UI controls to smaller components is a very good idea. They become too complex too fast!

**Comment by levnach** [comment]
Closing for now, to concentrate on open issues.

**Comment by MkazemAkhgary** [comment]
I need this for uwp. What should i do?

**Comment by Noemata** [comment]
Yes, please get this going with UWP.  After all, it's now the present (formerly the future).
