### ISSUE TITLE
SVG output in SvgGraphWriter does not support Octagon Shape - Not implemented exception

### ISSUE THREAD

**Issue by jlewis-rhimat** [Microsoft/automatic-graph-layout#117]
The WritePolyline method in SvgGraphWriter is currently not implemented.  In my case  svg output fails if the node is Shape.Octogon.

 void WritePolyline(Polyline poly, NodeAttr attr)
        {
            throw new NotImplementedException();
        }

Does anyone have an implementation of the WritePolyline method?

**Comment by levnach** [comment]
It should work now.

**Comment by jlewis-rhimat** [comment]
Thank you so much. Now outputting svg ok.
