### ISSUE TITLE
GViewer.CenterToPoint(Point point) not working

### ISSUE THREAD

**Issue by jlewis-rhimat** [Microsoft/automatic-graph-layout#118]
The method GViewer.CenterToPoint(Point point) is broken. (It worked in original MSAGL release). 

I'm trying to centre the graph display on a node using the following code

Microsoft.Msagl.GraphViewerGdi.DNode dNode = myNode as Microsoft.Msagl.GraphViewerGdi.DNode;
Microsoft.Msagl.Drawing.DrawingObject drawingObj = dNode.DrawingObject;
 this.gViewer1.CenterToPoint(drawingObj.BoundingBox.Center);

**Comment by levnach** [comment]
@jlewis-rhimat, please see if it works now.

**Comment by jlewis-rhimat** [comment]
Not quite working as before.

As I make additional calls to the CenterToPoint for other nodes, the diagram zooms out further and further with each additional call. I really want to move to each node position and retain the current zoom factor.

**Comment by levnach** [comment]
I think it works now. Can you check please?

**Comment by jlewis-rhimat** [comment]
Thanks Lev, now working ok.
