### ISSUE TITLE
GViewer strange zoom behaviour of ZoomToWindow

### ISSUE THREAD

**Issue by jlewis-rhimat** [Microsoft/automatic-graph-layout#120]
The Zoom To Window tool in GViewerGDI will often zoom in too much or will zoom out to much, behaviour is unpredictable from user perspective.

In the original MSAGL release the zoom to window would adjust the display to show the entire area covered by the zoom rectangle.

**Comment by levnach** [comment]
It should work now.

**Comment by jlewis-rhimat** [comment]
Thanks for the fix, the zoom to window feature now works. 

Can I request that you undo one of the changes you made when fixing this issue. Specifically,  
Commit e5fc7698
'DrawReversibleFrame is broken in winforms, stop using it' 

I believe this part of the feature works ok and provides very useful user feedback when selecting the zoom window.

**Comment by levnach** [comment]
I had a small repro (actually an MSDN sample) on a problem with 'DrawReversibleFrame which does not work on Windows 10 when the items are enlarged. Other users complained too that 'DrawReversibleFrame  is broken. I think it is safe to suppress this feature.

**Comment by jlewis-rhimat** [comment]
No worries, I will retain it in my local version. FYI, I'm using it successfully on windows 10 and have tried breaking it without success. Maybe, the issue was related to the other fixes you applied that certainly did correct its behaviour.
