### ISSUE TITLE
Sugiyama splines in Left To Right layout sometimes jump out to top left or bottom right corners of graph

### ISSUE THREAD

**Issue by jlewis-rhimat** [Microsoft/automatic-graph-layout#121]
I have a sample that I can demonstrate this behaviour with, based on the WindowsApplicationSample.

**Comment by levnach** [comment]
Please provide a sample.

**Comment by jlewis-rhimat** [comment]
Use this version of form1.cs in the WindowsApplicationSample.

[Form1.cs.zip](https://github.com/Microsoft/automatic-graph-layout/files/1127298/Form1.cs.zip)

Interestingly, the issue manifests itself differently when in debug or release build mode. SVG of release build graph attached.


[Issue_131_releasebuild.svg.zip](https://github.com/Microsoft/automatic-graph-layout/files/1127307/Issue_131_releasebuild.svg.zip)

**Comment by jlewis-rhimat** [comment]
Not sure if this is related but when using this graph, if I use the rerouteonly=true option in the layout settings form ( compiled with debug )  then I get a number of exception messages of the form 'unpadded polyline is not clockwise' 
![unpaddedpolylineexception](https://user-images.githubusercontent.com/13539211/28527351-24643944-7082-11e7-9b68-305e3ed05aec.PNG)

**Comment by levnach** [comment]
It is fixed now. Thank you for reporting this bug!

**Comment by jlewis-rhimat** [comment]
Thanks for fixing this issue. I've checked on my other large datasets and it all looks fine.
