### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by chandusekhar** [Microsoft/automatic-graph-layout#123]
![image](https://user-images.githubusercontent.com/9524949/28022742-a549c86e-65a9-11e7-929f-86ce4aa9cdfe.png)

Is there any way to draw ports like this. 

Nodes having child ports
show connected ports and free ports
Port constraint like port side

**Comment by levnach** [comment]
The ports are used internally but they are not exposed through the API.

**Comment by chandusekhar** [comment]
Are there any plans to add ports to API. This is really cool feature to have..

**Comment by levnach** [comment]
Sorry, there are no plans to support the ports.
