### ISSUE TITLE
The selected node border get thicker and thicker after open the layout settings window.

### ISSUE THREAD

**Issue by smwikipedia** [Microsoft/automatic-graph-layout#127]
![thick border](https://user-images.githubusercontent.com/999318/29263273-abce70b4-810a-11e7-8ad1-3b9c14cbbadd.png)

Repro Steps:
1. Click one node to select it.
2. Open the "Configures the layout algorithm settings" button in the toolbar.
3. Click the OK button in the "LayoutSettingsForm".
3.  Click the **same** node.

Expected: The node border should remain the same.
Actual: The node border get thicker and thicker as you go through the above steps.

**Comment by smwikipedia** [comment]
Currently, I work around this bug by manually setting the line width as below:

`dnode.Node.Attr.LineWidth = 1;`

**Comment by levnach** [comment]
Fixed now. Thank you!
