### ISSUE TITLE
Change the FillColor of a node in a rendered graph changes the border thickness

### ISSUE THREAD

**Issue by WDGrey** [Microsoft/automatic-graph-layout#129]
I have an existing rendered graph (in WPF GraphViewer) and I change the FillColor of a Node.  The border for that node becomes many times thicker.  If I zoom in and then click on the node, it rerenders to the correct border thickness.  Without zooming in, clicking on the node fills the entire node with the border color.

**Comment by levnach** [comment]
Is it still an issue? If it is can you provide a small sample?

**Comment by WDGrey** [comment]
This example shows the increased border thickness when the background color is changed and when a node is clicked on
[GraphExample.zip](https://github.com/Microsoft/automatic-graph-layout/files/1277727/GraphExample.zip)

**Comment by levnach** [comment]
It is fixed.
