### ISSUE TITLE
How to go to node in WPF control?

### ISSUE THREAD

**Issue by vdisasm** [Microsoft/automatic-graph-layout#136]
I want to scroll to some node, so that this node will be at top-center part of the WPF viewer.

I found some workaround, but it seems I don't handle scale correctly (it is 1 here):

```csharp
// entry is my node

var bbox = entry.BoundingBox;
var c = GraphViewer.GraphCanvas;
var vp = new Rectangle(
	new Point(0, 0),
	new Point(c.RenderSize.Width, bbox.Height));
GraphViewer.SetTransformOnViewportWithoutRaisingViewChangeEvent(1, bbox.Center, vp);
```

**Comment by levnach** [comment]
Sorry, is your intent to position a node at the view center?

**Comment by vdisasm** [comment]
I have graph with top-to-bottom layout and I'd like to place node at top vertically and center horizontally.

**Comment by levnach** [comment]
I have added a function Microsoft.Msagl.WpfGraphControl.GraphViewer.PointToCenter that will do the job. Call it with the node center as the parameter.

**Comment by vdisasm** [comment]
Thanks a lot.
