### ISSUE TITLE
Ranking layout failed for certain graphs

### ISSUE THREAD

**Issue by smwikipedia** [Microsoft/automatic-graph-layout#137]
I have a graph like this with Sugiyama layout:

![graph for ranking layout](https://user-images.githubusercontent.com/999318/29857255-5eacc1d2-8d8a-11e7-8c26-b684650756da.png)

When I use the GViewer to switch to Ranking layout. Below exception is thrown:

![ranking exception](https://user-images.githubusercontent.com/999318/29857272-70c23636-8d8a-11e7-9d89-c69f6bed184d.png)

I am using the Async Rendering of GViewer.

The GViewer.AsyncLayoutProgress event handler catches the "LayingOut" progress, but after that, the above exception is thrown.

I don't know how to provide more details. If you need more details. Please tell me how to. Thanks.

(For now, as a workaround, I have to remove the Ranking layout option from the source and recompile a new version.)

**Comment by levnach** [comment]
The crash should be fixed. However in Debug mode the routing on some graphs finds errors for this layout.
