### ISSUE TITLE
Why can I run `gViewer.Graph = graph` on a non-UI thread? Can I use it intead of async rendering?

### ISSUE THREAD

**Issue by smwikipedia** [Microsoft/automatic-graph-layout#142]
I know that a UI control should **only** be modified on the UI thread. If you modify a UI control on a non-UI thread and debug the application in Visual Studio, an exception will be thrown for [cross-thread UI modification](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls).

But as I tried, I can run `gViewer.Graph = graph` on a background worker thread. No exception is thrown in VS debug mode. So why?

If this is not an issue, maybe the **async** rendering mode for the GViewer is not necessary. Not to mention that it cause the dragging to slow down.

**Comment by levnach** [comment]
I fixed the dragging problem. The reason was that the changed entities were not Invalidated because of a bug in the GViewer and it had very little to do with threading.

**Comment by smwikipedia** [comment]
Thanks for fixing the issue. But I am still wondering if running `gViewer.Graph = graph` on a background worker thread is OK?

**Comment by levnach** [comment]
I am not sure. I have not tested it.

**Comment by smwikipedia** [comment]
I once used the [BackrgoundWorker](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls#making-thread-safe-calls-by-using-backgroundworker) from the .NET framework. I feel there's some similarity between GViewer async paradigm and the BackgroundWorker. So I use the GViewer in a similar way to BGW. Currently, I put the `gViewer.Graph = graph` in the BGW and no exception is thrown. I guess that's because this step doesn't involve UI manipulation.
