### ISSUE TITLE
BackColor is not respected

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#143]
I am trying to set the background color of GViewer but apparently this setting is ignored and the background always remains white. Am I writing the wrong code perhaps ?

>       this.gViewer.OutsideAreaBrush =  new SolidBrush(System.Drawing.Color.AliceBlue);
>       this.gViewer.BackColor = System.Drawing.Color.AliceBlue;

Thank you

**Comment by lafrank** [comment]
Crawling in the source code I found the solution, needed to use graph.Attr.BackColor instead of GViewer.BackColor. Tricky, though.

**Comment by WowItsDoge** [comment]
Did you find a solution to change the background of the graph control?

```cs
Microsoft.Msagl.Drawing.Graph graph = new Microsoft.Msagl.Drawing.Graph("graph");
graph.Attr.BackgroundColor = Microsoft.Msagl.Drawing.Color.Green;
```

Only changes the background of the graph, but not the background of the GraphViewerGdi control.
I am using this control in an WindowsFormsHost of a WPF application.

![stackoverflow](https://user-images.githubusercontent.com/16211590/40133059-d85b37f4-593e-11e8-9761-5269a8a30bae.PNG)

**Comment by levnach** [comment]
Have you tried gViewer.OutsideAreaBrush?

**Comment by levnach** [comment]
Yes, it is possible.
