### ISSUE TITLE
GraphMaps example crashes

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#145]
I built Lg.sln Release/x64 just as suggested, but when trying to load composer.msagl the application crashes with NullReferenceException.
Any idea please how to get it work, or another sample teaching the usage of GraphMaps ?
Thank you.

![image](https://user-images.githubusercontent.com/15701860/31306330-bcd22d52-ab4d-11e7-9d8e-4f421b37e472.png)
![image](https://user-images.githubusercontent.com/15701860/31306331-c2613ab0-ab4d-11e7-8ddd-6e176f7c8870.png)

**Comment by lafrank** [comment]
I finally found that Graph.GeometryGraph.directory property must be set, as the code does not check whether it is null or not. Not too nice indeed...
So the solution - or rather a workaround - is to add line 839 :

![image](https://user-images.githubusercontent.com/15701860/31310570-7c3c8d12-ab9a-11e7-8c42-6b4fa94fe2fe.png)

**Comment by levnach** [comment]
You are right, it was not nice. I removed GeometryGraph.directory which was a remainder of an experiment.

**Comment by lafrank** [comment]
Thank you.
