### ISSUE TITLE
Using Clusters

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#148]
From the code I infer that clusters are for logical grouping of nodes.

So I am trying to use clusters based on sample application FastIncrementalLayoutWithMdi, however, doing things in slightly different way. First of all, I primarily targeting MDS layout, because it generates a view resembling closer to my goals.

First of all, I am not sure, whether Clusters are supported with MDS. Are they ?

Secondly, I can see from the sample that using Clusters requires that GeometryGraph is generated prior to adding the nodes to clusters, otherwise the nodes won't have its GeometryNode set (remains null).
So far so good.
But I ran into another issue I can't resolve. What I try to do is like below. Add nodes to clusters based on some grouping logic :

![image](https://user-images.githubusercontent.com/15701860/31683201-9707b538-b37c-11e7-8aed-cddde9763e98.png)

Afterwards, depending on actual layout settings I try to perform layout. But executing the highlighted line I get the below exception :

![image](https://user-images.githubusercontent.com/15701860/31683101-3e0b0624-b37c-11e7-9ce8-84329e89fc16.png)

Could you Lev please help what is wrong here as I desperately try to generate a suitable layout but it seems to be atough nut.

Thank you !

**Comment by levnach** [comment]
What is the stack here? Is the Node here a cluster? Can you make sure that all GeometryGraph.Nodes have BoundaryCurve set?

**Comment by levnach** [comment]
Clusters are not supported by MDS.

**Comment by lafrank** [comment]
Node is a Core.Layout.Node, and its BoundaryCurve is null, this is the issue. Is it not created by Graph.CreateGeometryGraph() ?

![image](https://user-images.githubusercontent.com/15701860/31689165-e0fb5412-b38e-11e7-927b-50f8a33cb6c4.png)

By the way I am adding nodes as below:
![image](https://user-images.githubusercontent.com/15701860/31689310-50ff4d86-b38f-11e7-9a46-ae632f60ab33.png)

and

![image](https://user-images.githubusercontent.com/15701860/31689338-684c8db4-b38f-11e7-9140-ea4da355def9.png)

Is the above not enough to have some internal code set the BoundaryCurve ? 
How does this delegate and the Attr.Shape = DrawFromGeometry assignment relate to each other and when is this delegate called ? Why does not the CreateGeometryGraph() utilize them ? Or, why not the call 
`(new LayeredLayout(tree.GeometryGraph, (SugiyamaLayoutSettings)gsettings)).Run();`
performs this action ?

Ultimately and most importantly, how can I have the BoundaryCurve of a Node set ?

**Comment by levnach** [comment]
I am not sure why Node.BoundaryCurve is null. The scenario with NodeBoundaryDelegate works in NodesWithImages sample. Please make sure that you code in RenderRouterNodeBoundary is executed.
If you feel a change is needed please submit a pull request.

**Comment by lafrank** [comment]
I have realized recently that Node.BoundaryCurve was null because I set GraphViewer.AsyncLayout to true and was trying to access the property before layout generation completed.
