### ISSUE TITLE
WPF collapse subgraph error

### ISSUE THREAD

**Issue by Cedric-Paris** [Microsoft/automatic-graph-layout#151]
When I collapse a subgraph in a WPF Window, the hidden nodes are still handled by the ObjectUnderMouseCursor property : 
![untitledwindow](https://user-images.githubusercontent.com/15748526/31764182-c080c7fc-b4c0-11e7-8c1e-97eab7873ab0.jpg)

We can also drag the hidden node in the canvas -> it generate the exception below
![untitled](https://user-images.githubusercontent.com/15748526/31764204-cc4f2a42-b4c0-11e7-8548-c77744091e38.jpg)

This issue is reproducible in "WpfApplicationSample"

**Comment by levnach** [comment]
I fixed it. Thank you!

**Comment by Cedric-Paris** [comment]
Thank you very much for that quick fix ! 👍
