### ISSUE TITLE
WpfGraphControl VEdge Drawing.Style.Dashed issue

### ISSUE THREAD

**Issue by jerzy-d** [Microsoft/automatic-graph-layout#152]
I need some edges in my graph to be displayed as dashed lines. But only one of them is dashed.
I think the problem is in this VEdge method:

**internal double DashSize()** 
{ 
    var w = PathStrokeThickness; \
    var dashSizeInPoints = dashSize * GraphViewer.DpiXStatic; 
    _**return dashSize = dashSizeInPoints / w;**_ 
} 
After each edge drawing the static variable is updated, and its value is growing:
**_internal static double dashSize = 0.05; //inches_**

I changed DashedSize() method to (I downloaded msagl, and built on my machine):
**internal double DashSize()** 
{ 
    var w = PathStrokeThickness; \
    var dashSizeInPoints = dashSize * GraphViewer.DpiXStatic; 
    _**return dashSizeInPoints / w;**_ 
}
And now my all dashed edges are displayed.

**BTW. Thank you for this library. I am using it in all my projects requiring graph display.
Last year I switched to WPF and this is the first and only issue I had encountered.**

Thank you, Jerzy.

**Comment by levnach** [comment]
Nice catch! Thank you!
