### ISSUE TITLE
Weird MDS layout

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#153]
Can Lev please help me to understand why MDS algorithm creates a topology like below one ? There are many unreasonable node placements and edge crossings. What parameter shall I tune to achive a more concise a logical structure for the graph ? Is it related perhaps to different node sizes ?
Other layout algorithm looks even worse for me :-( 

Thank you.

![image](https://user-images.githubusercontent.com/15701860/32742563-1a0539a0-c8aa-11e7-89c8-263ab05e246d.png)

**Comment by levnach** [comment]
I do not have a good answer for the first question. I don't think that different node sizes play an important role here. I would try to change two properties of MDSLayoutSettings: PivotNumber ( make it larger, the max could be the number of nodes in the graph), and IterationsWithMajorization ( also make it larger than the default 30). 
In general, the problem of minimizing the edge crossings is hard. It is NP-complete even for a bipartite graph. But by looking at the image one can tell that some local heuristics can improve the drawing.

**Comment by lafrank** [comment]
Thanks Lev, tuning these parameters made it.
The edge crossings are less disturbing, tough. What is more confusing is the unreasonably far placement of a node to its direct neighbor.
Now that I increased those two parameters, anomalies like that reduced notably.

**Comment by levnach** [comment]
Laslo, can you please post the image you got after tuning the parameters?

**Comment by lafrank** [comment]
Sure, here it is :
![image](https://user-images.githubusercontent.com/15701860/32856464-34e4ead0-ca45-11e7-9a01-d439196ccd39.png)

**Comment by lafrank** [comment]
When I create a new graph with the code below I try to set the above mentioned parameters from code, however it is skipped for some reason.
This is how I do this:


![image](https://user-images.githubusercontent.com/15701860/35165060-1fe7245a-fd4d-11e7-800a-d5359817283c.png)

But later, when I open the property editor for the graph, I see different settings:

![image](https://user-images.githubusercontent.com/15701860/35165117-5607dfca-fd4d-11e7-96be-63e20f6f582e.png)
If I change the settings in that form and press OK, it works as expected and reopnening the property editor shows the values set earlier.

Can you please suggest what am I doing wrong ?
