### ISSUE TITLE
Graphviewer selection rectangle invisible

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#154]
I am not sure whether this was an issue or  just a missing feature, but I can't see a selection rectangle drawn in GraphViewer when I keep left mouse pressed while moving the mouse to select multiple nodes. At the end all nodes covered will be selected, only it is hard to tell in the meantime which node will or will not be included in the selection.

So is there some settings that need to be set/tuned to display the selection rectangle or is it missing completely ?

Thank you.

**Comment by levnach** [comment]
I disabled the rendering of the selection rectangle here https://github.com/Microsoft/automatic-graph-layout/commit/e5fc76985520788fdaf7ce07b6b18307c6781472, because of the Winforms bug. 
Thanks

**Comment by lafrank** [comment]
Thank you, I'll check the details.

**Comment by lafrank** [comment]
I revoked this commit in my fork and I can't see any issue with it. Can you please double check or elaborate what was wrong ?
Thank you.

**Comment by levnach** [comment]
https://www.codeproject.com/Questions/1054468/why-does-ControlPaint-DrawReversibleFrame-seem-to. This post explains the bug. The rectangle is rendered with the wrong offset sometimes.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
