### ISSUE TITLE
Can not use images with WPF 

### ISSUE THREAD

**Issue by cxdeus** [Microsoft/automatic-graph-layout#156]
Dear Lev,

First of all i want to appreciate your own work Msagl. You really did a great job! 
When i try to use NodesWithImages sample with WPF, images are not shown and also  when i use GraphViewer.DrawImage method but i can not use it.It throws an exception.
How i can display images with WPF?

Thanks a lot

**Comment by levnach** [comment]
I don't have experience with rendering images by using WPF, sorry.
