### ISSUE TITLE
Printing Issue

### ISSUE THREAD

**Issue by cxdeus** [Microsoft/automatic-graph-layout#158]
Dear Sir,
When i print out the graph, it only prints the current view.How can i print ot whole view of the graph?
Also if i want to change the width or height of the graph programmatically, it doesnt change width or heigth.how can i change the width or height of the graph programmatically?

Thanks a lot!

**Comment by levnach** [comment]
What viewer do you use?

**Comment by cxdeus** [comment]
i use GraphViewerGdi.GViewer

**Comment by levnach** [comment]
A way to print the whole view is to press "home" button, and then use the print dialog. 
In general, the layout algorithm decides on the layout size, however you can set graph.Graph.Attr.MinimalWidth, and graph.Graph.Attr.MinimalHeight.

**Comment by levnach** [comment]
In my experiment pressing the home button changes the view by bringing the zooming out on the whole graph. 
The effect of settings graph.Attr.MinimalWidth, and graph.Graph.Attr.MinimalHeight should be visible after calling the layout again.

**Comment by cxdeus** [comment]
Dear Lev,
Yes it does zooming out when i press the button.but it prints only the current view.
Actually what i want to is, to print the graph with print dialog after giving the height and width of the graph by A4 paper size.When i save the whole view as a jpeg or png it prints without problem.(it fits on A4 paper when i give exact sizes w)but when i want to print directly with print dialog it doesnt print whole graph even i give width or height of the graph.
Thanks a lot

**Comment by levnach** [comment]
I'm afraid it is not implemented.

sent from a phone, Lev

________________________________

**Comment by cxdeus** [comment]
ok..thanks
