### ISSUE TITLE
Influence arrow size and edge separation

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#160]
I am struggling to change the above two parameters on the graph, can you please help me to understand how to do this correctly ?  I tried setiting Edge attributes like below 
      
`thisEdge.Attr.Separation = 200;
thisEdge.Attr.ArrowheadLength = 200;`

but it does not work for me somehow, the arrows arestill too small and are too close to each other:
![image](https://user-images.githubusercontent.com/15701860/35166362-f2c6deb6-fd51-11e7-80e7-7b95e3ba6340.png)

Thank you in advance !

**Comment by lafrank** [comment]
Is it possible to influence the distance between multiple edges ? 
I managed to set arrow size with ArrowHeadLength.

**Comment by levnach** [comment]
It is BundlingSettings.EdgeSeparation. There is a bug reported when this value is increased.

**Comment by lafrank** [comment]
Thank you Lev, I'll check this out.
