### ISSUE TITLE
Node label isn't showed

### ISSUE THREAD

**Issue by foreverstupid** [Microsoft/automatic-graph-layout#165]
I want to make a node label that can be different from its ID. But if I set `Node.Label`, the label of the node disappears at all. That's my code:

```C#
var nd = new Microsoft.Msagl.Drawing.Node("node1");
nd.Attr.FillColor = Microsoft.Msagl.Drawing.Color.Red;
nd.Label = new Microsoft.Msagl.Drawing.Label("Realy Label");
nd.Label.Color = Microsoft.Msagl.Drawing.Color.Blue;
nd.Label.IsVisible = true;
```

And there is no any text on the node on the screen.
So how can I fix this?

**Comment by levnach** [comment]
Label.Text, I believe.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by foreverstupid** [comment]
No results. It doesn't help
```C#
nd.Label.Text = "Realy Label";
```

**Comment by levnach** [comment]
Sorry, it is node.LabelText

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by foreverstupid** [comment]
But `LabelText` is showed only in a black color and standart sfont size, and I can't change it. Moreover the class `Label` has a lot of useful fields, that can help me in design

**Comment by levnach** [comment]
This seems working 
 var n = graph.FindNode("7");
 n.LabelText = "seven";
 n.Label.FontSize *= 2;
 n.Label.FontColor = Color.AntiqueWhite;

**Comment by foreverstupid** [comment]
Ok, I have understood this scheme. Thank you very much!
