### ISSUE TITLE
Edge routing collapse on node move

### ISSUE THREAD

**Issue by lafrank** [Microsoft/automatic-graph-layout#173]
This issue is a continuation of original topic in #144 

I noted that multi-edge routing still does not always work and in some cases multi-edges collapsed to single edge between nodes.

While debugging the problem I realized that SplineRouter class detects node overlaps in graph, and if there are any overlaps it falls back to regular, simple edge routing instead of showing multiple edges.
Looking at SplineRouter.SplitOnRegularAndMultiedges() :

![image](https://user-images.githubusercontent.com/15701860/46247296-9b0efa80-c409-11e8-9fd1-cbcb3e1e0ebc.png)

Before digging even deeper into the code, could you @levnach please explain why this was required ? Is there any easy way to still use multi-edge routing despite of overlaps ?

Thank you in advance.

**Comment by levnach** [comment]
I think my logic was as follows: I do not have code for routing multi edges with node overlaps, but I still need to draw the edges. So I route them by using SplineRouter.

**Comment by lafrank** [comment]
Thank you for your quick reply.
