### ISSUE TITLE
SetupDisplayNodeIds - node.DebugId can not be compiled in release mode

### ISSUE THREAD

**Issue by FilipRychnavsky** [Microsoft/automatic-graph-layout#178]
\GraphLayout\Samples\FastIncrementalLayoutWithGdi\Form1.cs - method SetupDisplayNodeIds uses 
`node.DebugId = ((DrawingNode)node.UserData).Id;`
`DebugId` is defined in\GraphLayout\MSAGL\Core\Layout\Node.cs - but only in Debug mode
Filip

**Comment by levnach** [comment]
Thank you for reporting. I fixed it.
