### ISSUE TITLE
Port constraints in layout

### ISSUE THREAD

**Issue by toytonics** [Microsoft/automatic-graph-layout#181]
Hi there,
Does the layout algorithm respect input and output ports of edges? 

`Edge.cs` states the following:
> The member is used at the moment only when adding an edge to the graph

So I assume it doesn't? Any plans on implementing port constraints in the future?
There's some interesting research on this:
https://rtsys.informatik.uni-kiel.de/~biblio/downloads/papers/gd14.pdf or https://rtsys.informatik.uni-kiel.de/~biblio/downloads/papers/jvlc13.pdf

**Comment by levnach** [comment]
Sorry, there are no plans to implement this feature.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
