### ISSUE TITLE
Graph as an image object

### ISSUE THREAD

**Issue by sunilvangala** [microsoft/automatic-graph-layout#207]
Hi Lev,

Is there any way to get the graph as an image object?
I want to get the graph as a stream and use it at other places programmatically.

Thanks,
Sunil.

**Comment by levnach** [comment]
Hi Sunil,
Inside of GraphViewerGdi there is GraphRenderer that can write a graph to an Image.
It is also possible to use Dot2Svg to write a graph as a SVG file.
Thanks,
Lev

**Comment by sunilvangala** [comment]
Hi Lev,
Thanks for the response. I am looking for a method that can return the image object when I pass the graph. My requirement is to get the graph as an image and display it on a different form.
Thanks,
Sunil.

**Comment by levnach** [comment]
GraphRenderer saves a graph as an Image.

**Comment by sunilvangala** [comment]
Great. Thanks a lot, Lev. It worked.
