### ISSUE TITLE
which .net frame work is needed ?

### ISSUE THREAD

**Issue by ehsanwwe** [microsoft/automatic-graph-layout#229]
> Install-Package : Could not install package 'AutomaticGraphLayout.GraphViewerGDI 1.1.7'. You are trying to install this package into a project that targets 
> '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the 
> package author.

hello i  search alot but i cant find whats the reason of the error
thanks

**Comment by Oaz** [comment]
GraphViewerGDI is a Framework v4.7.2 project
cf https://github.com/microsoft/automatic-graph-layout/blob/master/GraphLayout/tools/GraphViewerGDI/GraphViewerGDI.csproj

**Comment by nessor** [comment]
I use it in a 4.8 project and it's still running!
