### ISSUE TITLE
Can the assemblies be strong name signed?

### ISSUE THREAD

**Issue by twsouthwick** [microsoft/automatic-graph-layout#231]
I want to include the project in Visual Studio as part of an extension and strong named assemblies are required. This would be a major breaking change, but required for a number of scenarios. Thanks!

**Comment by levnach** [comment]
I am not sure about this request. Strong naming probably can hurt some users. I would like to hear more opinions.

**Comment by twsouthwick** [comment]
Here's the guidance from the docs: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming. Yes, it can definitely cause problems if you are not used to them, and I can understand the hesitancy. However, these points lead me to always strong name sign:

- If you don't strong name, then anyone wanting to use the library from a strong-named app cannot do so
- If you do strong name, and someone does not strong name their app, they can continue to use it.

So, strong naming allows to reach the broadest audience. Most applications with extension models (such as VS) are strong name signed and so cannot consume libraries that are not.

I'm currently having to build my own version of the library for a project and would rather not. I'm interested if there is any other feedback for this.

**Comment by levnach** [comment]
@twsouthwick , can you please submit a pull request for this? Thank you!

**Comment by r-ramesh** [comment]
@levnach @twsouthwick Can you update the NuGet package to contain the strong name signed binaries?
