### ISSUE TITLE
Arrow heads

### ISSUE THREAD

**Issue by sreebhargava143** [microsoft/automatic-graph-layout#238]
- Arrowheads are not exactly inverted triangles(solid anchor), because of thickness issues sometimes it becomes a dot, to be precise when the thickness is minimal the arrowhead becomes a small dot, maybe because of smudging of the black color of the arrowhead.

- How to change the arrowhead style?

**Comment by levnach** [comment]
Please have a look at method GraphViewerGdi.DrawArrow. It supports several types. Please add a type that you need.

**Comment by sreebhargava143** [comment]
> DrawArrow

**Comment by sreebhargava143** [comment]
> Please have a look at method GraphViewerGdi.DrawArrow. It supports several types. Please add a type that you need.

GraphViewerGdi.DrawArrow method is not available in that namespace.

**Comment by levnach** [comment]
Sorry, GraphLayout/tools/GraphViewerGDI/Draw.cs.
`internal static void DrawArrow(Graphics g, Brush brush, P2 start, P2 end, double lineWidth,
                                       ArrowStyle arrowStyle) {
            switch (arrowStyle) {
                case ArrowStyle.NonSpecified:
                case ArrowStyle.Normal:

                    DrawNormalArrow(g, brush, ref start, ref end, lineWidth);
                    break;
                case ArrowStyle.Tee:
                    DrawTeeArrow(g, brush, ref start, ref end, lineWidth);
                    break;
                case ArrowStyle.Diamond:
                    DrawDiamondArrow(g, brush, ref start, ref end, lineWidth);
                    break;
                case ArrowStyle.ODiamond:
                    DrawODiamondArrow(g, brush, ref start, ref end, lineWidth);
                    break;
                case ArrowStyle.Generalization:
                    DrawGeneralizationArrow(g, brush, ref start, ref end, lineWidth);
                    break;
                default:
                    throw new InvalidOperationException();
            }
        }
`

**Comment by sreebhargava143** [comment]
Thank you Levnach...

**Comment by levnach** [comment]
@sreebhargava143 , can you please submit a pull request with the new arrow style?
