### ISSUE TITLE
[Question] Enforcing a top to bottom layout?

### ISSUE THREAD

**Issue by SMTStuck** [microsoft/automatic-graph-layout#247]
I have a simple sample of three nodes and two edges, and am usinng only the core layout engine and doing all rendering myself. 

```
Node 1 connects to Node 2
Node 3 connects to Node 2
```

The code below gives the following layout:

![Result](https://user-images.githubusercontent.com/28392792/88323192-c5862200-cd19-11ea-8def-5aab74b6f0ff.png)

I've browsed the code to the best of my ability, but I cannot see anything that enforce a top to bottom layout as follows:

![Expected](https://user-images.githubusercontent.com/28392792/88323279-e2baf080-cd19-11ea-9f49-ec0e6936dc5f.png)

I know I can transform the graph, but I cannot do this unless the graph is always laid out bottom to top. So, is there a way to enforce the graph to always lay out top to bottom, or can I at least rely on the graph consistently being laid out bottom to top?

Thank you.

Accompanying code:
```
List<Node> nodes = new List<Node>();
List<Edge> edges = new List<Edge>();

nodes.Add(new Node(CurveFactory.CreateRectangle(50, 50, new Microsoft.Msagl.Core.Geometry.Point(0, 0)), "1"));
nodes.Add(new Node(CurveFactory.CreateRectangle(50, 50, new Microsoft.Msagl.Core.Geometry.Point(0, 0)), "2"));
nodes.Add(new Node(CurveFactory.CreateRectangle(50, 50, new Microsoft.Msagl.Core.Geometry.Point(0, 0)), "3"));
edges.Add(new Edge(nodes[0], nodes[1]));
edges.Add(new Edge(nodes[2], nodes[1]));

IEnumerable<GeometryGraph> subGraphs = GraphConnectedComponents.CreateComponents(nodes, edges);
SugiyamaLayoutSettings layoutSettings = new SugiyamaLayoutSettings();
foreach (GeometryGraph subgraph in subGraphs)
{
	LayeredLayout layout = new LayeredLayout(subgraph, layoutSettings);
	subgraph.Margins = layoutSettings.NodeSeparation + 50;
	layout.Run();
}
Microsoft.Msagl.Layout.MDS.MdsGraphLayout.PackGraphs(subGraphs, layoutSettings);
```

**Comment by levnach** [comment]
I believe , the SugiyamaScheme starts exploring depth first from nodes[0] and will reverse each edge that leads back to the visited ones.
Maybe it is not the best approach but that is how it works. 
So, if you have a DAG, to avoid reversed edges add the nodes in the topological sort order.

**Comment by SMTStuck** [comment]
Much appreciated.
