### ISSUE TITLE
msaglsilverlight doesn't contain subfolders

### ISSUE THREAD

**Issue by birbilis** [Microsoft/automatic-graph-layout#27]
Seems somebody has linked files from various folders flat inside msaglsilverlight

Since there are two LayerInfo.cs files, one at \msagl\Layout\LargetLayout\ and one at \msagl\Layout\Layered\Ordering\ this causes the following warning:

Warning	1	The file '..\msagl\Layout\Layered\Ordering\LayerInfo.cs' could not be added to the project.  Cannot add a link to the file LayerInfo.cs. There is already a file of the same name in this folder.	msaglsilverlight

Instead project subfolders should be added and then the linked files dragged into them. Only side-effect of this is that it creates respective empty folders (if they only contain links) under that Silverlight project, but this should resolve the issue I see above, since I see those two LayerInfo.cs files are different (have different namespace). Now only one of them is compiled in the library and can be used from other projects that refer to this library

**Comment by birbilis** [comment]
a quick way to make the missing LayerInfo.cs appear is to add a subfolder to that project, move the existing file link (use drag-drop) into the subfolder, then save project and close/reopen solution (or right click and unload/reload the project). Then the 2nd LayerInfo.cs appears, that one outside of the subfolder where the other LayerInfo.cs is. Then can rename subfolder and organize the rest of the linked files too (possibly use two subfolders, LargeLayout and LayeredLayout or something like that?)

**Comment by levnach** [comment]
I currently am seeing only one LayerInfo.cs in the project. Closing the issue.

**Comment by birbilis** [comment]
Please open the .csproj in text editor and you'll see two

Also compiler shows the warning I wrote about above if you select warnings to be shown

See the workaround above, need to move file to separate project (virtual) folder (since those are linked files), ten savw and reopen project and you'll see the second (different) file appear

**Comment by levnach** [comment]
Thanks, you are right. It is fixed now. I did not follow your advice about the subfolders, sorry.
