### ISSUE TITLE
[QUESTION] node with multi-line text

### ISSUE THREAD

**Issue by aPlacuzzi** [microsoft/automatic-graph-layout#270]
Hi all,

Is it possible to put the text inside a node in multiple lines?

Example:
the node text is "foo bar" and I want to visualize it like this:
"foo
bar"

**Comment by levnach** [comment]
I think "foo\nbar" is going to work

**Comment by aPlacuzzi** [comment]
I have tried modifying your sample `MinWpfApp`.
Wpf view renders it correctly as you can see here:
![MinWpfApp-screenshot](https://user-images.githubusercontent.com/30112038/100590104-4078ce00-32f4-11eb-8fb1-4d9a3d10d624.png)

But if try to export the graph as svg image, I get this result:
![MinWpfApp-export](https://user-images.githubusercontent.com/30112038/100590349-8df53b00-32f4-11eb-9ee6-faf0f0064d10.png)

To export the graph as svg image I have added this code at the end of the sample:
``` c#
var gr = new GraphRenderer(graph);
gr.CalculateLayout();
SvgGraphWriter.Write(graph, path, null, null, 11);
```
Here the svg file exported:
[MinWpfApp-export.svg.txt](https://github.com/microsoft/automatic-graph-layout/files/5614896/MinWpfApp-export.svg.txt)

Any ideas for the different behaviour?

**Comment by levnach** [comment]
@aPlacuzzi!

Obviously, there are at least two bugs there. One us not preserving the end of the line in a label , and another not keeping the octagon shape. It is open source; why don't you try to fix them?

**Comment by aPlacuzzi** [comment]
@levnach 
Ok, I should have found the two bugs. 
I'll try to fix them, then I'll open a PR.
