### ISSUE TITLE
Viewer.AddNode(dNode, true); => slow node drag and drop

### ISSUE THREAD

**Issue by khoailangdo** [microsoft/automatic-graph-layout#284]
I add node in the following way:
> ` IViewerNode dNode = Viewer.CreateIViewerNode(node, pos, null);`

> `Viewer.AddNode(dNode, true);`

When dragging and dropping the node is very slow.
But I add node by: Graph.AddNode() and drag and drop is very smooth.
Did I do anything wrong?

**Comment by MVoloshin** [comment]
I confirm that issue. Happens even in GraphEditor.cs sample

**Comment by levnach** [comment]
Fixed by https://github.com/microsoft/automatic-graph-layout/commit/8b9f6c2d924ed20f95a6c4b819e2ff3ab757b8fb
