### ISSUE TITLE
Graph appears twice while zooming out using AutomaticGraphLayoutControl (WPF)

### ISSUE THREAD

**Issue by fxsth** [microsoft/automatic-graph-layout#286]
I just started working with WPF and MSAGL, so please forgive me if thats an obvious beginners fault, but I couldn't find a related issue:
When using the AutomaticGraphLayoutControl from the latest nuget-package (WpfGraphControl 1.1.11) in my MainWindow.xaml, I can zoom out and in the background appears the same graph as in the initial view. The background graph disappears when resizing the window manually.
The problem occurs not only in my project, I can replicate it in the "MinWpfCoreApp"-sample by replacing the old package WpfCoreGraphControl with AutomaticGraphLayout.WpfGraphControl, see screenshot:

![image](https://user-images.githubusercontent.com/62942815/124951854-0737d780-e014-11eb-95d3-47168764f14a.png)

Creating a GraphViewer instead and using it via BindToPanel() seems to be a workaround.

**Comment by levnach** [comment]
I think I fixed it with the last commit https://github.com/microsoft/automatic-graph-layout/commit/2e18785853235b859383ba38f64220bd6cf9642c. I have not published a new nuget though.

**Comment by fxsth** [comment]
Yes, it fixed it. Thank you, Lev! Is the nuget package still maintained by @paulovila ?

**Comment by paulovila** [comment]
Hi Lev let me know if you are ok to publish it

**Comment by levnach** [comment]
Hi Paulo, please do!

**Comment by paulovila** [comment]
Will do tomorrow, sorry, I'm travelling
