### ISSUE TITLE
[question] How can I use it with GtkSharp

### ISSUE THREAD

**Issue by michaelkruglos** [microsoft/automatic-graph-layout#287]
How can I use MSAGL library with GtkSharp?

**Comment by levnach** [comment]
I think nobody tried it. There is an effort of porting MSAGL to JavaScript at https://github.com/msaglJS/msagl-js. I hope the JavaScript version will be more portable.

**Comment by michaelkruglos** [comment]
Is there example of creating a layout independent of rendering subsystem? I'm not sure I can find it.

**Comment by levnach** [comment]
Have a look, for example, at GraphLayout\Samples\DrawingFromGeometryGraphSample\DrawingFromGeometryGraphSample.csproj.

**Comment by michaelkruglos** [comment]
Thanks. Those were helpful.

**Comment by levnach** [comment]
Have you succeeded to use Msagl with GtkSharp?

**Comment by michaelkruglos** [comment]
Yes. I took the code from  CommonDrawingUtilsForSamples and modified it to work with GtkSharp and CairoSharp (drawing library). Some routing methods didn't work very well. I tested it on Windows in the mean time, and I'll try to build/run it on Linux as well. When I have more time, I may want to contribute a GtkSharp sample to this repository.

**Comment by levnach** [comment]
Can you leave some instructions of how you integrated MSAGL with GtkSharp? It is especially interesting for Linux.

**Comment by michaelkruglos** [comment]
I added a pull request #289
