### ISSUE TITLE
How to disable tooltips?

### ISSUE THREAD

**Issue by NiklasVJM** [microsoft/automatic-graph-layout#300]
Hi! I have WPF app, using this automatic-graph-layout. Is there a way to disable those tooltips all together?

Especially I would like to disable tooltips for nodes, which does not have any label text. Is this possible?

**Comment by levnach** [comment]
I fixed it by adding property GraphViewer.CreateToolTipForNodes. I pushed the change to github, but I have not updated the NuGet, actually have never done this.
