### ISSUE TITLE
[Question] Recalculate Edge Splines & Subgraph Labels

### ISSUE THREAD

**Issue by MrHaribo** [microsoft/automatic-graph-layout#327]
### Question 1

I have a Graph with many bi-directional edges. The initial rendering of the graph looks fine. As soon as I drag a node with the mouse in the graph viewer, all edges that where previously rendered as splines turn into straight edges (see image below). This behavior makes the graph much harder to read. Is there a way to recalculate the spline edges after mouse dragging?

_Original layout:_
![image](https://user-images.githubusercontent.com/5812189/183653678-96d130ac-e489-4030-87ef-8ea75915884c.png)

_After dragging:_
![image](https://user-images.githubusercontent.com/5812189/183653912-936b641c-9958-4e12-a3da-e9adbd7587d8.png)

### Question 2

In the nugget release (1.1.12) the labels on subgraphs are not working. I found out that there was a PR (https://github.com/microsoft/automatic-graph-layout/pull/313) but it seems that this was not released yet. I tried to integrate the library from source but experienced many problems regarding stability. Is there any information when these changes will be release?

**Comment by levnach** [comment]
1) Try holding Shift key when dragging: It should kick off the routing with splines. It is not the default mode because of the possible lag in the calculations. You can make all the dragging necessary without holding the shift and then hold the shift and make a short dragging motion again. 
2) I am looking for volunteers to produce the nugget.

**Comment by MrHaribo** [comment]
Thank you for your fast reply.

1. That is very good to know and solves our problems.
2. Unfortunately i don't have experience with nugget feeds, so hopefully someone who does will take care of this. The tooltips on mouse over are working so this is a work around for the time being.

**Comment by MrHaribo** [comment]
Thank you for your fast reply.

1. That is very good to know and solves our problems.
2. Unfortunately i don't have experience with nugget feeds, so hopefully someone who does will take care of this. The tooltips on mouse over are working so this is a work around for the time being.
