### ISSUE TITLE
Microsoft.Msagl.GraphViewerGdi.GViewer.AddEdge commented

### ISSUE THREAD

**Issue by acarv** [Microsoft/automatic-graph-layout#34]
In Microsoft.Msagl.GraphViewerGdi.GViewer there was an AddEdge method :  

    public Microsoft.Msagl.Drawing.Edge AddEdge(Microsoft.Msagl.Drawing.Node source, Microsoft.Msagl.Drawing.Node target, bool registerForUndo)  

That method is now commented.
I do use MSAGL, in a former version, in a simple application where I want to add edges by selecting two nodes and invoke a contextual menu to select an edge type. I just need a straight edge between the two nodes.
It seems that the new version is only allowing to draw edges by dragging. I really think this is not the best approach as it steals a lot of flexibility from the tool. One of its strengths is to allow usage in whatever interaction model the programmer wants.
Can somebody help? Maybe I'm not seeing it right. I'm just beginning to explore version 3 (but upgrade is being painful...). 
Best regards
André de Carvalho

**Comment by levnach** [comment]
Thanks Andre, I fixed it.  Lev

**Comment by acarv** [comment]
WOW! Great code and a 7 hour fix?!? Amazing!
Thanks Lev.
Andre'
