### ISSUE TITLE
Simplest way to export a graph as a PNG?

### ISSUE THREAD

**Issue by snarlynarwhal** [microsoft/automatic-graph-layout#344]
Hi, is it possible to export a graph to PNG without using Forms?

**Comment by levnach** [comment]
Got it from chatGpt. I have not checked that it works

using Microsoft.Msagl.Drawing;
using System.Drawing;
using System.Drawing.Imaging;

Graph graph = new Graph("MyGraph");
Node node1 = graph.AddNode("Node1");
Node node2 = graph.AddNode("Node2");
Edge edge = graph.AddEdge("Node1", "Node2");

// Set up the drawing settings
graph.Attr.BackgroundColor = Microsoft.Msagl.Drawing.Color.White;
graph.Attr.LayerDirection = Microsoft.Msagl.Drawing.LayerDirection.LR;

// Create a bitmap to draw on
Bitmap bitmap = new Bitmap(800, 600, PixelFormat.Format32bppArgb);

// Create a graphics object from the bitmap and clear it
Graphics graphics = Graphics.FromImage(bitmap);
graphics.Clear(System.Drawing.Color.White);

// Create a renderer and set its rendering surface to the graphics object
Microsoft.Msagl.GraphViewerGdi.GraphRenderer renderer = new Microsoft.Msagl.GraphViewerGdi.GraphRenderer(graph);
renderer.GraphBorder = 10; // Optional: add some padding around the edges of the graph
renderer.Render(graphics);

// Save the bitmap as a PNG file
bitmap.Save("MyGraph.png", ImageFormat.Png);

**Comment by snarlynarwhal** [comment]
I'll give that approach a try, thanks!
