### ISSUE TITLE
How to create: Title, Subtitle on nodes and Tooltip on edge

### ISSUE THREAD

**Issue by powergleb** [microsoft/automatic-graph-layout#348]
Hi!
I'm trying to build a graph that will represent DB relations so I would like each node to have a title with the table name and sub title which will represent the different keys of the table and on the edge a string with the relation such as:"each table1 may have many table2".

is it possible and if so how?

Thanks!

Required functionality

Show table names, with a background color different than the background of the key names
Show key names
Lines describing relations and their direction between tables.
Tooltip with textual description of relations

https://github.com/powergleb/link-visualizer
![unnamed](https://github.com/microsoft/automatic-graph-layout/assets/58367952/2416267e-ce1f-4dca-a765-77c21bb263d6)

**Comment by levnach** [comment]
It is possible. If you use GraphViewerGDI then you need to override DNode.DrawNodeDelegate, as in NodesWithImages example. 
Otherwise, you might just use the geometry engine. In any case your coed is responsible for the rendering.

**Comment by powergleb** [comment]
Thank you! I got it all!
