### ISSUE TITLE
NuGet Packages

### ISSUE THREAD

**Issue by anno0** [microsoft/automatic-graph-layout#359]
Is it possible to get new NuGet package releases?
The current file is almost 2 years old!

https://www.nuget.org/packages/AutomaticGraphLayout.WpfGraphControl/

**Comment by levnach** [comment]
I published new NuGets: https://www.nuget.org/packages/Msagl/1.2.1, https://www.nuget.org/packages/Msagl.Drawing/1.2.1, https://www.nuget.org/packages/Msagl.WpfGraphControl/1.2.1, and https://www.nuget.org/packages/Msagl.GraphViewerGDI/1.2.1.

**Comment by levnach** [comment]
Good point. The new packages are the official release. I could not just update the previous packages of @paulovila  because of the permission. Referencing the new packages will be very helpful.

**Comment by snechaev** [comment]
PR with updated readme is ready: https://github.com/microsoft/automatic-graph-layout/pull/384
