### ISSUE TITLE
Support nested graphs?

### ISSUE THREAD

**Issue by MarkNicholls** [microsoft/automatic-graph-layout#364]
Does the library support scenarios where a node has a graph inside it?

e.g. like

![image](https://github.com/microsoft/automatic-graph-layout/assets/3265689/a8f72aa0-bff2-4d2f-ae1c-c6815deaa181)

(thats not actually what I want it for, but its close enough)
(I'm hoping because its effectively a recursive structure that its either directly possible or not too awful to implement?

**Comment by levnach** [comment]
Yes, it does. 
![image](https://github.com/microsoft/automatic-graph-layout/assets/5377127/e1a65cf6-4747-42bd-a462-f17c525fd040)
I just loaded GraphLayout\Test\MSAGLTests\Resources\DotFiles\LevFiles\clust.dot from msagl repository by runing TestForGdi.exe.
