### ISSUE TITLE
How to set space between points where Edges connected to Shape

### ISSUE THREAD

**Issue by lukasLata** [microsoft/automatic-graph-layout#366]
Hi,
When multiple Edges connected into one Shape, I have very small space between Edges points on the Shape border. It is possible set larger space?
My layout setup:
            LayoutHelpers.CalculateLayout(graph,
                new FastIncrementalLayoutSettings {
                    EdgeRoutingSettings = {
                        EdgeRoutingMode = EdgeRoutingMode.Rectilinear,
                        CornerRadius = 0
                    },
                    NodeSeparation = 50, // Minimum space between nodes
                    AvoidOverlaps = true,
                }, null);

![image](https://github.com/microsoft/automatic-graph-layout/assets/163389810/964e1269-09f5-4a46-a232-6a1bc3ec62f7)

Thanks a lot.

**Comment by levnach** [comment]
I pushed a change. Try 
LayoutHelpers.CalculateLayout(graph,
new FastIncrementalLayoutSettings {
EdgeRoutingSettings = {
EdgeRoutingMode = EdgeRoutingMode.Rectilinear,
CornerRadius = 0,
EdgeSeparationRectilinear = yourEdgeSeparation
}

**Comment by lukasLata** [comment]
Thanks, it looks like ok.
