### ISSUE TITLE
Using WpfGraphControl. Want to export SVG.

### ISSUE THREAD

**Issue by MichaelHoffmeisterFesto** [microsoft/automatic-graph-layout#372]
Hello!
Thank you for maintaining this. I am successfully using WpfGraphControl to visualize production bill-of-materials (BOMs). I want to export SVG.

However, the WpfGraphControl does not seem to seem to assign layout information to the nodes, so that 

```
var svgWriter = new SvgGraphWriter(writer.BaseStream, drawingGraph);
svgWriter.Write();
```

does render very small elements and no node text (no Label.Width given).

Can you help?

![image](https://github.com/user-attachments/assets/39f9441e-d387-489b-84aa-840c36e2a3b0)

**Comment by levnach** [comment]
I committed a fix. I hope it works now.

**Comment by festo-i40** [comment]
Thank you, Sir!
Will your commit end up in a new nuget version somehow in the future? 
(I am asking because adding source-code testwise to my 60+ project solution is not that easy).

**Comment by levnach** [comment]
Somehow, I have not produced a single nuget. Please feel free to produce one.

**Comment by levnach** [comment]
I produced new NuGets https://www.nuget.org/packages/Msagl/1.2.1, https://www.nuget.org/packages/Msagl.Drawing/1.2.1, https://www.nuget.org/packages/Msagl.WpfGraphControl/1.2.1, and https://www.nuget.org/packages/Msagl.GraphViewerGDI/1.2.1.

**Comment by MichaelHoffmeisterFesto** [comment]
Thank you, Sir!

Want to let you know the result (see below). The nodes are a little bit on the tight side (I am using the graph produced by the layout of the WPF; do not know how to duplicate/ re-layout it).

![Image](https://github.com/user-attachments/assets/5d403067-b169-4396-9744-5f14172115d3)
