### ISSUE TITLE
Crash on collapsing subgraphs

### ISSUE THREAD

**Issue by ATrefzer** [microsoft/automatic-graph-layout#373]
Hi, I want to report an crash with collapsing a sub graph.

I use the current version of the repository (commit b199357).

**Note:**
It broke in commit: 0cc1abe61d5069f50b87f920f9190c9a8fd573fb
In the commit before it worked.

You can reproduce it with following example:

![grafik](https://github.com/user-attachments/assets/4204b038-236b-4b1f-abd7-469fd7da561b)

While you can collapse Model C the other crash. I think it happens when the edge goes to the cluster itself and not to an inner node.

The exception occurs in the file SplineRouter in method CalculatePortsToShapes.
![grafik](https://github.com/user-attachments/assets/11913f82-cc23-410b-bead-8e7f34322c40)

I used following lines to build the graph:

```
          Subgraph subGraph = null;
          Subgraph parentSubGraph = null;
          Node newNode = null;
          var graph = new Graph("test");
          var structA = new Subgraph("StructA");
          var modelC = new Subgraph("ModelC");
          var modelB = new Subgraph("ModelB");
          graph.RootSubgraph.AddSubgraph(structA);
          graph.RootSubgraph.AddSubgraph(modelC);
          graph.RootSubgraph.AddSubgraph(modelB);
          newNode = graph.AddNode("Fill");
          parentSubGraph = structA;
          parentSubGraph.AddNode(newNode);
          newNode = graph.AddNode("MethodOnModelC");
          parentSubGraph = modelC;
          parentSubGraph.AddNode(newNode);
          newNode = graph.AddNode("_structA");
          parentSubGraph = modelB;
          parentSubGraph.AddNode(newNode);
          graph.AddEdge("Fill", "ModelB");
          graph.AddEdge("MethodOnModelC", "ModelB");
          graph.AddEdge("_structA", "StructA");
```

**Comment by levnach** [comment]
I fixed the crash, but another change is needed to reroute more edges on the cluster collapse/opening.

**Comment by levnach** [comment]
Fixed by https://github.com/microsoft/automatic-graph-layout/commit/d098806ea640986f21e2d997d3b741d8b231da3f.
