### ISSUE TITLE
Exception when displaying Graph in WPF via GraphViewer

### ISSUE THREAD

**Issue by MartinBischoff** [microsoft/automatic-graph-layout#379]
In my WPF application I update the text of edge labels of a graph in real time.

Once a while the following exception is thrown:
![Image](https://github.com/user-attachments/assets/bf0c1787-d639-4110-b349-06c80f2d8ae0)

Is is this a known error in the conversion of the graph to wpf inPostLayout()?

Or  this due to a race condition between my graph update and graph rendering?
If it is a thread safety issue, is there an event that is raised when the updated graph has been fully rendered in wpf?

Sometimes my graph also looks like this:
![Image](https://github.com/user-attachments/assets/f7ea57c1-1b37-4ff4-bd1d-2f4c5911865d)
Generally the "Input" node is never drawn within its subgraph.

**Comment by levnach** [comment]
I am not sure how to reproduce this.

**Comment by MartinBischoff** [comment]
The reason for the weird graph and the exception was that I had two nodes with identical IDs "Input" in my graph.
It was not a thread safety issue. The PostLayout() routine works flawlessly.
