### ISSUE TITLE
[Question] WpfGraphConrol + GraphViewerGDI in one project?

### ISSUE THREAD

**Issue by TihonchukArtyom89** [microsoft/automatic-graph-layout#383]
Hi! I am working with MSAGL in WPF project and some features what I need is implemented in GraphViewerGDI. When I add GraphViewerGDI NuGet packages it throwing errors CS0433 on some types (Graph, Node, Edge etc.). Is there a way to use this  packages in one project?

**Comment by levnach** [comment]
It should not be a problem, I think. Maybe you need to qualify the types.

**Comment by TihonchukArtyom89** [comment]
Try to qualify the types, but that is not helping.

**Comment by levnach** [comment]
Please provide an example showing the problem.

**Comment by TihonchukArtyom89** [comment]
Sure. Here it is on link: https://dropmefiles.com/I46jK 
Because example is ~70 Mb.

**Comment by TihonchukArtyom89** [comment]
Sure. Here it is on link: https://dropmefiles.com/d24xY
Because example is ~70 Mb.

**Comment by alexkuznetsov** [comment]
@TihonchukArtyom89 Hi there  :-)

Can you check the archive at the link?
I changed the package list by replacing AutomaticGrapthLayout.*** packages with MSGAL.*** packages.
The application can be built without problems, but it crashes with a null reference exception.


[TestMsaglWPFApplication.zip](https://github.com/user-attachments/files/18163525/TestMsaglWPFApplication.zip)

**Comment by TihonchukArtyom89** [comment]
@alexkuznetsov  Thank you for bringing this news to my attention. I will study this point carefully. Indeed, the difference in the authors of the packages bothered me quite a lot. )

**Comment by TihonchukArtyom89** [comment]
@levnach  like @alexkuznetsov  said problem was in old nuget packages with diferent authors. At first sight at building errors was not detected. Thank you for your work)
