### ISSUE TITLE
Coordinates of all nodes from a default location of a node

### ISSUE THREAD

**Issue by varghesep** [Microsoft/automatic-graph-layout#42]
I'm able to get the coordinates of the nodes with **GeometryGraph**, but they are -ve for X and large +ve for Y. For example, I see (x, y)  = (-630, 700) which can't be plotted on the browser. I can do the adjustment, but then I have to apply the same to the edges also.

Can I specify the default location of a node and the coordinates of the other nodes and edges can be calculated based on that?

**Comment by levnach** [comment]
There is no option to specify the default location of a nodes. However, after a layout calculation you can apply GeometryGraph.Transform. It works on the edges too.

**Comment by varghesep** [comment]
I tried with the following code, but the transformation is not working.

```javascript
            var layeredLayout = new LayeredLayout(graph, settings);
            layeredLayout.Run();

            graph.Transform(new PlaneTransformation(1, 0, -2.5, 0, 1, 3.675));
```

**Comment by levnach** [comment]
It seems working. Please have a look at CommonDrawingUtilsForSamples.DrawingUtilsForSamples.SetGraphTransform. In this method I use GeometryGraph.Transform to place the graph into the client rectangle.

From the other side, you don't have to use GeometryGraph.Transform. Usually your client window's rectangle will be different from the graph bounding box anyway, so you will need to use some transformation on your graphics.

**Comment by varghesep** [comment]
Yes. It is working. I had to use larger values like 100 and -400 to make it work.

```javascript
graph.Transform(new PlaneTransformation(1, 0, 100, 0, 1, -400));
```

The diagram looks like below:

![gl](https://cloud.githubusercontent.com/assets/12233474/9813113/696fe5c8-5848-11e5-9910-c7562abd191d.PNG)

**Comment by levnach** [comment]
MSAGL does calculate the edge geometry. It uses a sequence of Bezier segments to present the edge curve which is trimmed by the node boundaries. It also, optionally, can calculate the arrowhead at the source or at the target of the edge. 
See, for example, CommonDrawingUtilsForSamples.DrawingUtilsForSamples.DrawEdge. 
Do you have to draw a polyline? The disadvantage of a drawing with polylines is that the polyline corners attract attention, but, at the same time, do not convey any interesting information about the graph.

**Comment by varghesep** [comment]
Traditionally the family tree charts have polylines in the shape of an elbow to connect the nodes to show the parent-child relationship. [Here is an example](https://gist.github.com/mbostock/2966094) that shows it.

I'm not sure introducing another node in between the nodes can help solve this problem? Phylotree may be a right place to integrate this logic.

**Comment by levnach** [comment]
MSAGL does not have this functionality. Phylotree will produce this kind of layout
http://research.microsoft.com/en-us/um/redmond/groups/cue/phylodet/images/PhyloDet.png
Sorry, I have no plans to add the functionality that you require.
