### ISSUE TITLE
WPF GraphViewer throws exception if Graph.Attr.LayoutDirection is set

### ISSUE THREAD

**Issue by matthagenbuch** [Microsoft/automatic-graph-layout#43]
I have a simple WPF application which displays a 2-node graph with an edge between the two nodes.  If I set the `Attrs.LayoutDirection` for the graph to `LayoutDirection.LR`, the `GraphViewer` throws a `NullReferenceException` upon setting the graph.  The null reference is the `Node.BoundaryCurve` member in the method call `Node.Transform(PlaneTransformation)`.

See code below:

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Loaded += MainWindow_Loaded;
        }

        private void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            GraphViewer graphViewer = new GraphViewer();
            graphViewer.BindToPanel(Panel);
            Graph graph = new Graph();

            graph.AddEdge("A", "B");
            graph.Attr.LayerDirection = LayerDirection.LR;
            graphViewer.Graph = graph; // throws exception
        }
    }

**Comment by levnach** [comment]
I was able to repro it and "pushed" a fix. It should work now.

**Comment by matthagenbuch** [comment]
Confirm fixed on my end, thanks!
