### ISSUE TITLE
Aspect Ratio not being used

### ISSUE THREAD

**Issue by matthagenbuch** [Microsoft/automatic-graph-layout#44]
In the AspectRatioSample, changing the aspect ratio, simple stretch setting, and min width/height doesn't seem to have any effect on the graph.  No combinations of values that I have tried result in the graph layout changing from the original layout.

![image](https://cloud.githubusercontent.com/assets/7414485/9822145/0a57ed90-587c-11e5-869c-055dc664396c.png)

**Comment by levnach** [comment]
Sorry, I cannot find this sample. But I checked the functionality with  AspectRatioTests and played with it by loading dot file with Test01 and changing the aspect ratio by using by layout setting. The functionality seemed working, although I had to suppress an assert to pass the tests.
