### ISSUE TITLE
SameLayerSample not working

### ISSUE THREAD

**Issue by varghesep** [Microsoft/automatic-graph-layout#45]
I know that it has worked sometime back, but the sample **SameLayerSample** that shows nodes in the same layer is not working.

This is what I see now. I use the latest sources from GitHub.

![layer](https://cloud.githubusercontent.com/assets/12233474/9982389/6cb6e0c4-5fa0-11e5-9cef-3f4035b11536.PNG)

**Comment by levnach** [comment]
Do you mean, that A has to be positioned between B and C? I agree, but sorry, I will not fix it soon.

**Comment by varghesep** [comment]
As per this [ticket](https://github.com/Microsoft/automatic-graph-layout/issues/39), it was fixed once.
