### ISSUE TITLE
merge drawing nodes with normal ones.

### ISSUE THREAD

**Issue by arisco** [Microsoft/automatic-graph-layout#46]
Hi, 
congrats for msagl, It looks nice.
 I'm developing a graph using msagl library in c#.

I have the next problem: I am not able to merge nodes with images (Shape.DrawFromGeometry) with normal shapes nodes ().
when I do it the normal ones disappear from the graph.
I have just modify the sample "NodesWithImages.csproj" to get the most easy example.

 private void InitGraph() {
            Graph drawingGraph = new Graph();
           
            drawingGraph.AddEdge(leavesId, creekId);
            drawingGraph.AddEdge(leavesId, treeId);
            drawingGraph.AddEdge(leavesId, wId);
            drawingGraph.AddEdge("uno","otro");
            foreach (DrawingNode node in drawingGraph.Nodes) {
                if (!node.Id.Equals("uno"))
                {
                    node.Attr.Shape = Shape.DrawFromGeometry;
                    node.DrawNodeDelegate = new DelegateToOverrideNodeRendering(DrawNode);
                    node.NodeBoundaryDelegate = new DelegateToSetNodeBoundary(GetNodeBoundary);
                }
                else
                {
                    node.LabelText = "bla";
                    node.Attr.Shape = Shape.Diamond; 
                    node.DrawNodeDelegate = null;
                    node.NodeBoundaryDelegate = null;

                }
                
            }

            double width = leaves.Width;
            double height = leaves.Height;

            drawingGraph.Attr.LayerSeparation = height / 2;
            drawingGraph.Attr.NodeSeparation = width / 2;
            double arrowHeadLenght = width / 10;
            foreach (Microsoft.Msagl.Drawing.Edge e in drawingGraph.Edges)
                e.Attr.ArrowheadLength = (float)arrowHeadLenght;
            drawingGraph.LayoutAlgorithmSettings = new SugiyamaLayoutSettings();
            viewer.Graph = drawingGraph;
        }

So the node called "uno" should appear as a diamond node. But it doesn't get draw.
When I debug the code I looks right, like diamond node until the end of debug. At the end it presents me like this: 
![captura](https://cloud.githubusercontent.com/assets/14803073/10049082/41eccc1e-6216-11e5-8e05-c705451d460f.PNG)

thanks!!!!

**Comment by levnach** [comment]
I fixed it. Please check out the new version.
Thanks

**Comment by arisco** [comment]
Now works perfect.

thanks to you!
