### ISSUE TITLE
AddLeftRightConstraint doesn't work

### ISSUE THREAD

**Issue by arisco** [Microsoft/automatic-graph-layout#47]
Hi,

I'm trying to order de nodes inside my graph but, 
I'm using for that (I have tried to ways)

 
            var settings2 = graph.LayerConstraints;

            settings2.PinNodesToSameLayer(new Node[]{ graph.FindNode("0_3"),
                                          graph.FindNode("0_1"),graph.FindNode("0_2")  });
            settings2.AddLeftRightConstraint (
                                            graph.FindNode("0_1"),
                                            graph.FindNode("0_2") ); // this crash

and this other way:

            Microsoft.Msagl.Layout.Layered.SugiyamaLayoutSettings settings1 =
                               graph.LayoutAlgorithmSettings as
                                     Microsoft.Msagl.Layout.Layered.SugiyamaLayoutSettings;
            graph.CreateGeometryGraph();
            settings1.AddLeftRightConstraint(graph.FindGeometryNode("0_1"), 
                                            graph.FindGeometryNode("0_2")); //this crash

In both of the I get the same message.

![error1](https://cloud.githubusercontent.com/assets/14803073/10052138/91f87668-6225-11e5-917b-d0f9f058b36e.PNG)

The real problem is that after closing the alerts the Graph load with the correct order and presentation.

the only thing I need is to learn how to eliminate that Alert.

![captura2](https://cloud.githubusercontent.com/assets/14803073/10052365/ccd723fa-6226-11e5-995b-ceb0d5d9371a.PNG)

Thanks!!!

**Comment by levnach** [comment]
I would like to understand why this assertion happens. But for the time being if you just use the Release build there will be no assertions.

**Comment by arisco** [comment]
very good!
