### ISSUE TITLE
Change background image of gviewer doesn't work

### ISSUE THREAD

**Issue by arisco** [Microsoft/automatic-graph-layout#54]
Hi,

trying with FindEmptySpotSample project in samples 

I have put the gViewer back color to "Maroon"
in preview looks great:

![captura](https://cloud.githubusercontent.com/assets/14803073/11208798/808b437e-8d1d-11e5-96ac-639648ac515d.JPG)

But when I execute the program always looks Gray background color.

![captura2](https://cloud.githubusercontent.com/assets/14803073/11208852/c67ad3a4-8d1d-11e5-938c-c3b44785dc62.JPG)

How could I change that property

**Comment by Udellgames** [comment]
In Form1.cs edit the method `CreateGraph()` as follows:

        private void CreateGraph() {
            Graph graph = new Graph("graph");
            graph.Attr.BackgroundColor = Color.Maroon;
            Edge edge = (Edge)graph.AddEdge("S24", "27");
            edge.LabelText = "Edge Label Test";
    ....

The key is that the graph holds its own representation of the color it should render. By setting `graph.Attr.BackgroundColor` you can override this.

**Comment by arisco** [comment]
Thanks for replaying Udellgames!

But sorry it doesn't work form me.
Why?
because thats not de propertie that I want to change and the propertie is that it doesn't work is this.
   gViewer.Graph = graph;
   gViewer.BackColor = System.Drawing.Color.Maroon;

I want to set de background o the gviewer. not the background of the graph.
background in gviewwen always appears in gray color.


check the blue marked area

![captura3](https://cloud.githubusercontent.com/assets/14803073/11266219/43c3dae6-8ea3-11e5-8b0a-a59457258c2f.JPG)

**Comment by Udellgames** [comment]
Ah I see, sorry I misunderstood. Thanks for updating with a diagram, I shall see if I can work out what's doing that.

**Comment by arisco** [comment]
great!!
thanks for your time

**Comment by levnach** [comment]
Please try setting gViewer.OutsideAreaBrush. Thanks
![untitled](https://cloud.githubusercontent.com/assets/5377127/11279909/20766a0e-8ea8-11e5-8e69-3921e4705782.png)

**Comment by arisco** [comment]
It works!!

Thanks!!!
