### ISSUE TITLE
automatic-graph-layout core Failure

### ISSUE THREAD

**Issue by arisco** [Microsoft/automatic-graph-layout#59]
Hi,

Testing my program, something strange has happened.
With the FormPrincipal program alive (without closing it)
I dispose the form that contains references to a gviewer and graph. (I call FormGraph.dispose() method)

my next operation is reload the same form that contains a graph, with diferent content (diferent number of nodes, but is the same form)
I do a new instance of the form.

It crassesh here in DrawingPanel.cs [automatic-graph-layout core class] :

  void ProcessPan(MouseEventArgs args) {
            if (ClientRectangle.Contains(args.X, args.Y)) {
                if (args.Button == MouseButtons.Left) {
                    gViewer.Transform[0, 2] = mouseDownTransform[0, 2] + args.X - mouseDownPoint.X;
                    gViewer.Transform[1, 2] = mouseDownTransform[1, 2] + args.Y - mouseDownPoint.Y;
                    gViewer.Invalidate();
                } else
                    GViewer.Hit(args);
            }
        }

telling that mouseDownTransform is null.

Why could it be?

here is the stacktrace

************** Texto de la excepción **************
System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Microsoft.Msagl.GraphViewerGdi.DrawingPanel.ProcessPan(MouseEventArgs args) en C:\Aitor\SVN\graph-layout\automatic-graph-layout.git\trunk\GraphLayout\tools\GraphViewerGDI\DrawingPanel.cs:línea 261
   en Microsoft.Msagl.GraphViewerGdi.DrawingPanel.OnMouseMove(MouseEventArgs args) en C:\Aitor\SVN\graph-layout\automatic-graph-layout.git\trunk\GraphLayout\tools\GraphViewerGDI\DrawingPanel.cs:línea 210
   en System.Windows.Forms.Control.WmMouseMove(Message& m)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by levnach** [comment]
Sorry for the delay. I fixed it.
