### ISSUE TITLE
Panning problem (Samples\WpfApplicationSample)

### ISSUE THREAD

**Issue by vdisasm** [Microsoft/automatic-graph-layout#61]
Sometimes when I start dragging outside of graph it either won't move or move to unexpected position.
It's fine if I start dragging inside of graph or re-size window first or zoom-in/zoom-out first.

**Comment by vdisasm** [comment]
I guess I've found what's the problem.

In GraphViewer.cs (GraphCanvasMouseMove) pan can be started even if _mouseDownPositionInGraph was not initialized. And initial delta for panning is incorrect of course.

A little workaround:

[diff.txt](https://github.com/Microsoft/automatic-graph-layout/files/163868/diff.txt)

**Comment by levnach** [comment]
Thank you very much. I am taking this in:-)
