### ISSUE TITLE
Nodes with the same name

### ISSUE THREAD

**Issue by mbibim** [Microsoft/automatic-graph-layout#62]
Hello,

first very thanks for this .NET component. Incredibly usefull !!!

I have a question - i need to create two nodes with the same name in the same graph but it doesn't seem to be possible with the method - AddEdge(string, string)

Is there another solution for that ?

Thank you :)

**Comment by levnach** [comment]
Hi,
Let us say you need to create two nodes with the label "foo".
It can be done like that 
graph.AddNode("id1").LabelText = "foo";
graph.AddNode("id2").LabelText = "foo";

**Comment by mbibim** [comment]
Hi,
thanks so much for your answer but my question was not enough clear sorry. 

In fact it was; how is it possible using the AddEdge function ?

There's no function AddEdge(Node, Node) but only AddEdge(string, string) ...

Regards

**Comment by uxmal** [comment]
Does this work?
```
graph.AddNode("id1").LabelText = "foo";
graph.AddNode("id2").LabelText = "foo";
graph.AddEdge("id1", "id2");
```

**Comment by mbibim** [comment]
Sounds good !! will try thank you.
