### ISSUE TITLE
Absolute positioning of nodes with overlap removal

### ISSUE THREAD

**Issue by Marluwe** [Microsoft/automatic-graph-layout#63]
Hey everyone,

first of all I want to thank you all for this great tool. I have taken a look at the automatic-graph-layout and I am wondering if the following is possible:
Using the GraphViewer for WPF: Can I place nodes at given coordinates right at the beginning, such that one of the given layouts would move them relatively to avoid any overlaps?

The FastIncrementalLayout seems quite promissing with the use of the LockPosition class. But I have not managed to place my nodes correctly at first place (esp. without grouping nodes corresponding to connected components). It appears to me that the given locks are ignored in the initial layout.

Best
Markus

**Comment by levnach** [comment]
Hi Marcus,
You can do it by using Microsoft.Msagl.Core.Layout.ProximityOverlapRemoval.MinimumSpanningTree.OverlapRemoval.

**Comment by Marluwe** [comment]
Thank you for your reply. That was exactly what I needed.
