### ISSUE TITLE
GraphMaps cause AV with Triangle.c line 5795

### ISSUE THREAD

**Issue by K2** [Microsoft/automatic-graph-layout#64]
I can render graph's just fine with the same input, 32 & 64 bit builds.

Details from output window on debug builds;

> starting processing a graph with 613 nodes and 613 edges
> LayoutConnectedGraphWithMds: nodes 7 edges 7
> LayoutConnectedGraphWithMds: nodes 7 edges 7
> LayoutConnectedGraphWithMds: nodes 85 edges 85
> LayoutConnectedGraphWithMds: nodes 166 edges 166
> LayoutConnectedGraphWithMds: nodes 281 edges 281
> LayoutConnectedGraphWithMds: nodes 53 edges 53
> LayoutConnectedGraphWithMds: nodes 14 edges 14
> done with LayoutConnectedComponents
> done with LayoutConnectedComponents
> done with LayoutConnectedComponents
> done with LayoutConnectedComponents
> done with LayoutConnectedComponents
> 
> done with LayoutConnectedComponents
> 
> done with LayoutConnectedComponents
> 
> zoom level = 1 with the grid size = 18912.8093279865
> zoom level = 2 with the grid size = 9456.40466399327
> zoom level = 4 with the grid size = 4728.20233199663
> zoom level = 8 with the grid size = 2364.10116599832
> zoom level = 16 with the grid size = 1182.05058299916
> zoom level = 32 with the grid size = 591.025291499579
> 
> Removing overlaps
> ..
> Initializing Cdt input
> 
> Writing Cdt input

 # Call Site
00 triangle!incircleadapt(void)+0x6fa3 [c:\users\files\downloads\triangle\triangle.c @ 5795]
01 triangle!counterclockwiseadapt(void)+0xbcf [c:\users\files\downloads\triangle\triangle.c @ 5217]
02 triangle!orient3dadapt(void)+0x726c [c:\users\files\downloads\triangle\triangle.c @ 6319]
03 KERNEL32!BaseThreadInitThunk+0x22
04 ntdll!RtlUserThreadStart+0x34

The below fragment is where windbg pop's up...

``` C
      negate = -ady;
      Two_Product(bdxtail, negate, ti1, ti0);
      negate = -adytail;
      Two_Product(bdx, negate, tj1, tj0);
      Two_Two_Sum(ti1, ti0, tj1, tj0, v3, v[2], v[1], v[0]); // <== Crash is here
      v[3] = v3;
      abtlen = fast_expansion_sum_zeroelim(4, u, 4, v, abt);

      Two_Product(adxtail, bdytail, ti1, ti0);
      Two_Product(bdxtail, adytail, tj1, tj0);
```

Attached is the file which causes the crash, thanks.

[pointssegments8720.poly.txt](https://github.com/Microsoft/automatic-graph-layout/files/183384/pointssegments8720.poly.txt)

**Comment by levnach** [comment]
We are in a process to avoid using Triangle here. I think it will happen in a month or so. I would suggest to use GraphMaps with 64 configurations since it requires a lot of memory.

**Comment by K2** [comment]
OK, to clarify, GraphViewer is good both 32/64.  It's just the GraphmapsViewer which fails on both 32/64 (fetch was from yesterday).  Were you suggesting that there is a workaround I may be able to try for the GraphMapsViewer?  I had previously generated useful GraphMaps (which are really neat btw), so there may be some way to organize the input but I was not sure what "magic" I did last time when they worked (also it was a much larger set of graphmap that was working).

**Comment by levnach** [comment]
No, I don't have a workaround here, sorry, and Triangle is not my code. What I am saying that we will not use Triangle in the future so this bug will go away.

**Comment by K2** [comment]
OK thanks that's what I thought. Any idea how long on replacing it? I
really liked the graphmaps when they worked for me... ;)

**Comment by levnach** [comment]
About a couple if months I'd say

**Comment by mwherman2000** [comment]
Where can I find the GraphMaps source code?

**Comment by levnach** [comment]
LG.sln in the GraphLaout directory builds GraphMaps. Otherwise the sources for GraphMaps are quite spread out in MSAGL. On the geometry level the directory GraphLayout / MSAGL/Layout/LargeGraphLayout  contains the relevant sources.

**Comment by K2** [comment]
I'd love to do some more coding around the graphmaps, do you think there are any workarounds for this issue?  Is it allowed to port that code to C#, C++/CLI or something that might handle the its internal errors more gracefully?

**Comment by K2** [comment]
I had some really cool GraphMaps I'd love to post when this get's sorted out :( any plans to bypass triangle yet?

**Comment by levnach** [comment]
GraphMaps does not use Triangle anymore.
