### ISSUE TITLE
Where are the dlls?

### ISSUE THREAD

**Issue by Hypernut** [Microsoft/automatic-graph-layout#67]
Hi, i would like to use MSAGLwith Powershell. On the Frontpage it says:  

```
> The package contains the following:
>     Layout engine (Microsoft.MSAGL.dll)
>     Drawing module (Microsoft.MSAGL.Drawing.dll)
>     Viewer control (Microsoft.MSAGL.GraphViewerGDIGraph.dll) 
```

But it does not. 
If I have to somehow built them myself, a short step-by-step guide would be great, as I have really no clue on how to do that. 
Thank you!

**Comment by cgravill** [comment]
If you have or can install the .net dev tools you could build the dlls:

1) Checkout the repository

2) Load up PowerShell ISE and navigate to $\automatic-graph-layout\GraphLayout

3) run this PowerShell

```PowerShell
#build MSAGL libaries
$msbuild = "C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe"
Invoke-Expression "$msbuild GraphLayout.sln"

#Reference Windows Forms
Add-Type -AssemblyName System.Windows.Forms

#Reference the libaries we just built
Add-Type -Path ".\tools\GraphViewerGDI\bin\Debug\Microsoft.Msagl.dll"
Add-Type -Path ".\tools\GraphViewerGDI\bin\Debug\Microsoft.Msagl.Drawing.dll"
Add-Type -Path ".\tools\GraphViewerGDI\bin\Debug\Microsoft.Msagl.GraphViewerGdi.dll"

#Create a host
$Form = New-Object system.Windows.Forms.Form

#The MSAGL graph
$Graph = New-Object Microsoft.Msagl.Drawing.Graph

#Fill in some edges
$Graph.AddEdge("47","58")
$Graph.AddEdge("70","71")

#A GDI based viewer for the MSAGL graph
$GViewer = New-Object Microsoft.Msagl.GraphViewerGdi.GViewer

$GViewer.Graph = $Graph
$Form.Controls.Add($GViewer)

$Form.ShowDialog()
```

With that it gives me an interactive viewer:
![image](https://cloud.githubusercontent.com/assets/1099725/14232086/3f87eace-f994-11e5-9c13-04ccc17a2997.png)

I adapted this from the one many great samples in:
$\\automatic-graph-layout\GraphLayout\Samples
(that should show you how to run a layout, or use WPF and much more!)

There are plans to publish a Nuget which would great, see #4 

Hope this helps!

**Comment by Hypernut** [comment]
That worked like a charm, thanks! Is there an overview of the available classes and their members?

**Comment by levnach** [comment]
Sorry, this description is out of date. To build the dlls please open GraphLayout.sln with Visual Studio 13  or higher and build it





On Sun, Apr 3, 2016 at 3:15 AM -0700, "Hypernut" <notifications@github.com> wrote:





Hi, i would like to use MSAGLwith Powershell. On the Frotpage it says:

> The package contains the following:
>     Layout engine (Microsoft.MSAGL.dll)
>     Drawing module (Microsoft.MSAGL.Drawing.dll)
>     Viewer control (Microsoft.MSAGL.GraphViewerGDIGraph.dll)

But it does not.
If I have to somehow built them myself, a short step-by-step guide would be great, as I have really no clue on how to do that.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Microsoft/automatic-graph-layout/issues/67

**Comment by Hypernut** [comment]
But it worked. Or are there sideeffects i did not see yet? 
I got Visual Studio 2015 but only used it as a WYSIWYG-Forms editor for WPF forms.  When i open GraphLayout.sln there, i get tons of errors and warnings...

**Comment by levnach** [comment]
Is this issues still relevant?

**Comment by Hypernut** [comment]
Of course. You never answered my question. :) What is the downside compiling with msbuild vs. compiling with  VS 13?

**Comment by levnach** [comment]
I don’t think there is a downside.  Can you please provide the build log with errors that you see when compiling from VS 13?

**Comment by Hypernut** [comment]
I have 2015. Thing is, all the warnings and errors are in German. Can i pull an english log out of there somehow?

**Comment by levnach** [comment]
I think you can change the Display language of VS by going to Tools->Options->International Settings.

**Comment by Hypernut** [comment]
`Severity	Code	Description	Project	File	Line	Suppression State
Warning		Could not find rule set file "MinimumRecommendedRules.ruleset".	Test01			
Error	CS0234	The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	4	Active
Error	CS0234	The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	5	Active
Error	CS0234	The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	10	Active
Error	CS0246	The type or namespace name 'GraphLink' could not be found (are you missing a using directive or an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	29	Active
Error	CS0246	The type or namespace name 'GraphCategory' could not be found (are you missing a using directive or an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	30	Active
Error	CS0246	The type or namespace name 'GraphLink' could not be found (are you missing a using directive or an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	38	Active
Error	CS0246	The type or namespace name 'GraphCategory' could not be found (are you missing a using directive or an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	53	Active
Error	CS0246	The type or namespace name 'GraphNode' could not be found (are you missing a using directive or an assembly reference?)	DgmlParser	\DgmlParser\DGMLParser.cs	75	Active
Warning	CS0162	Unreachable code detected	Msagl	D:\tmp\automatic-graph-layout-master - Kopie - Kopie - Kopie\GraphLayout\MSAGL\Core\Layout\ProximityOverlapRemoval\MST\OverlapRemoval.cs	513	Active
Warning		The primary reference "System.Net.Http", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Net.Http" or retarget your application to a framework version which contains "System.Net.Http".	PhyloTreeFromGeometrySample			
Warning		The primary reference "System.Net.Http", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Net.Http" or retarget your application to a framework version which contains "System.Net.Http".	SameLayerSample			
`

**Comment by Hypernut** [comment]
The list looks horrible when posted here. I pasted it here: [LINK](http://www.wepaste.com/hypernut/)

**Comment by Hypernut** [comment]
The above were the errors recieved when OPENING the sln.
I added the ones that appear when i try to BUILD the solution to the same wepaste: [LINK](http://www.wepaste.com/hypernut/)

**Comment by levnach** [comment]
Your both links are the same. Anyway, you need to get VSSDK.GraphModel. Please try the following. 
Pull with git the new version and reload the solution, try rebuilding. 
If it does not work try installing VSSDK.GraphModel inside VS by going to Tools->NuGet Package Manager->Package Manager Console. Rebuild.
If it does not work remove define GraphModel from the build options of DgmlParser.csproj and from TestWpfViewer.csproj.

**Comment by Hypernut** [comment]
Can I problematically **deselect** an edge, which has been selected by mouse-click? 
I tried setting  SelectedForEditing = $false and MarkedForDragging = $false, but without success.

**Comment by Hypernut** [comment]
Can I programmatically **deselect** an edge, which has been selected by mouse-click? 
I tried setting  SelectedForEditing = $false and MarkedForDragging = $false, but without success.

**Comment by levnach** [comment]
Closing this issue. Hypernut, I will open another issuer with your question.
