### ISSUE TITLE
Rectangular EdgeRouting: Edges through nodes

### ISSUE THREAD

**Issue by Marluwe** [Microsoft/automatic-graph-layout#68]
Dear developers of the automatic-graph-layout,

I noticed a strange behavior using the EdgeRoutingMode Rectilinear (a description how I construct the graph/viewer is given below the video).
I am working on a bigger project, where the following happens (see video):
When I am dragging a node from the left or the right crossing vertical parts of edges does not move them and edges of the node might cross other nodes. This does not happen with vertical movements.
This only happens for a few nodes inside slightly bigger graphs (> 20 nodes).

![2016-04-04 17h18_31](https://cloud.githubusercontent.com/assets/15705744/14253327/5e658878-fa8b-11e5-9ef4-c26d2c6f8e71.gif)

I am going through the following steps:
*) Construct a GraphViewer (WpfGraphControl) and bind it to a panel
*) Construct a Graph "Pregraph":
`PreGraph = new Graph();
           PreGraph.LayoutAlgorithmSettings = new FastIncrementalLayoutSettings();
           this.NeedToRemoveOverlapOnly = true;
           PreGraph.LayoutAlgorithmSettings.EdgeRoutingSettings.EdgeRoutingMode =                   Microsoft.Msagl.Core.Routing.EdgeRoutingMode.Rectilinear;`
*) Avoid layout by the viewer: `this.NeedToCalculateLayout = false;`

-- After the window containing the panel for the viewer is loaded:

*) Generate  a set of nodes, add them to the "PreGraph" and register the LabelCreators
*) Add the edges to the "PreGraph"
*) Create the geometryGraph: `PreGraph.CreateGeometryGraph();`
*) For the viewer set: `NeedToCalculateLayout = false;
NeedToRemoveOverlapOnly = true;`
*) For each edge update the BoundaryCurve (using CurveFactory methods)
*) `viewer.Graph = PreGraph`
*) An iteration over all nodes modifying their positions
*) Call ` Microsoft.Msagl.Core.Layout.ProximityOverlapRemoval
                    .MinimumSpanningTree.OverlapRemoval
                    .RemoveOverlaps(nodes, 50);`
*) Call `LayoutHelpers.RouteAndLabelEdges(m_GraphViewer.PreGraph.GeometryGraph, 
                    m_GraphViewer.PreGraph.LayoutAlgorithmSettings, GraphViewer.PreGraph.GeometryGraph.Edges);
                foreach (var item in m_GraphViewer.Entities)
                {
                    m_GraphViewer.Invalidate(item);
                }`

**Comment by levnach** [comment]
Sorry, there are no plans to fix it.
