### ISSUE TITLE
Fix creating SugiyamaLayoutLogger

### ISSUE THREAD

**Issue by vdisasm** [Microsoft/automatic-graph-layout#71]
In one of the constructors in LayeredLayoutEngine.cs there is missing auto-creation of logger (when Reporting enabled). It could lead to null reference exception when Reporting enabled.

So I added it by analogy with other version of constructor.

There's also 3rd version of constructor I didn't touch.

[1.diff.txt](https://github.com/Microsoft/automatic-graph-layout/files/226546/1.diff.txt)

**Comment by levnach** [comment]
Fixed. Thank you!
