### ISSUE TITLE
What is the purpose of these properties

### ISSUE THREAD

**Issue by Hypernut** [Microsoft/automatic-graph-layout#72]
Hi, there are some LayoutAlgorithm properties, for which I can not figure out from the examples what they do:
**MDS**:
- Number of pivots
- CallIterationsWithMajorizationThreshold
- ClusterMargin
- Exponent
- NumberofInterationswithMajorization

**Sugiyama**

- Fast X-coordinate assignment algorithm threshold 
_(actually: how can I set this via a LayoutAlgorithmSettings object, I can only find it in the LeyoutSettings-Dialog in the viewer)_

- Group Split

**Edge Routing Settings:**
- IncrementalRoutingThreshold
- KeepOringinalSpline
- UseObstacleRectangles

**Comment by levnach** [comment]
Answered in https://github.com/Microsoft/automatic-graph-layout/issues/69
