### ISSUE TITLE
AutoScroll is not working

### ISSUE THREAD

**Issue by rakisaionji** [Microsoft/automatic-graph-layout#73]
The AutoScroll property is not working in WinForms, I have not tried in WPF yet, 
I have forced with gViewer1.AutoScroll = true; but it's still not working.

The property itself is working well in many earlier versions of MSAGL, and the outdated GLEE.
With the current version, it is not working anymore.

**Comment by Hypernut** [comment]
What is it supposed to do?

**Comment by rakisaionji** [comment]
To show ScrollBars when zoomed in the graph. Like this: 
[Microsoft GLEE Demo App](http://i.imgur.com/j6bsHmY.png)
(Image taken from the outdated GLEE demo)

I know we have the Pan tool, but having option to allow showing ScrollBars is for user satisfaction and more convenience.

**Comment by levnach** [comment]
This is by design. It seems that any design decision leaves somebody unhappy:-)
