### ISSUE TITLE
Reset graph position in the viewer

### ISSUE THREAD

**Issue by mbibim** [Microsoft/automatic-graph-layout#77]
Hello,

After using the zoom feature, it is possible to reset the zoom size using the _zoomfactor_ attribute and set to 1 :)

That is said, when i move my graph in the viewer using _PanButtonPressed_ attribute, how can i reset my graph to its original position in the viewer ?

thank you

**Comment by levnach** [comment]
There is a home button on the top left.

**Comment by mbibim** [comment]
thank you. I remember that but my question was programmaticaly ... I need to do that in another situation.

**Comment by levnach** [comment]
This should work

gViewer.Transform = null;

gViewer.DrawingPanel.Invalidate();

**Comment by mbibim** [comment]
ty so much. i Will try it asap. 😀

**Comment by mbibim** [comment]
that works fine. Ty Lev :)
