### ISSUE TITLE
MouseWheelZoom and Cursor

### ISSUE THREAD

**Issue by mbibim** [Microsoft/automatic-graph-layout#78]
Hello all,

The more time i spend using this librairy, the more i love it :) and the more i have questions :/

The first one is : When the "PanButtonPressed" is set to True, the cursor looks like a hand. Is it possible to set it back to default cursor ?

The second one is about the Zoom on MouseWheel. In my application, it works only if i click first in the background of my graph. And if i click on a node or arrow, it doesnt work anymore - i need to click again in the background. Is it normal ? and is it possible to activate it all the time ?

thank you for your help

**Comment by levnach** [comment]
One need to dig into GViewer.cs to fix these issues. I cannot do it right now.

**Comment by mbibim** [comment]
ok - Will Check and try to find something, ty

**Comment by mbibim** [comment]
Solve the problem with a Focus() forced.
