### ISSUE TITLE
Move graph programmatically 

### ISSUE THREAD

**Issue by brasio** [Microsoft/automatic-graph-layout#79]
I would like to move my graph programmatically (for example with scrollbars) or even to center the position of a selected node. It seems that there is a gViewer.Transform method which could do this, but I cannot figure out how to use it or even if there is a better approach.

Thanks for your suggestion!

**Comment by levnach** [comment]
This should work.
gViewer.Transform = yourTransform;
gViewer.DrawingPanel.Invalidate(); 

GViewer_MouseWheel shows a usage.

**Comment by brasio** [comment]
Thanks!

**Comment by WowItsDoge** [comment]
Has anyone a example for a transformation?
`gViewer.Transform = yourTransform;`

Like how to make a horizontal translate transformation for 100 px.

**Comment by levnach** [comment]
There are methods Microsoft.Msagl.GraphViewerGdi.GViewer.Pan() that do the job
