### ISSUE TITLE
SvgGraphWriter problem

### ISSUE THREAD

**Issue by patente** [Microsoft/automatic-graph-layout#81]
This class does not write nodes which are subgraphs. I was trying to introduce this function with code:

```
WriteSubGraphs();  //new method
WriteEdges();
WriteNodes();

...................................
void WriteSubGraphs()
{
   WriteComment("subgraphs");
   foreach (Subgraph ab in _graph.RootSubgraph.Subgraphs) WriteSubGraph(ab);
   WriteComment("end of subgraphs");
}

void WriteSubGraph(Subgraph subgraph)
{
   WriteNode(subgraph);
   foreach (Subgraph sg in subgraph.Subgraphs) WriteSubGraph(sg);
}
```
The problem is that all subgraphs in the svg file are not correectly vertical aligned, they are too much bottomed

**Comment by patente** [comment]
It seems that the problem is inside TransformGraphByFlippingY method:

```
public void TransformGraphByFlippingY() {
var matrix = new PlaneTransformation(1, 0, 0, 0, -1, 0);
 _graph.GeometryGraph.Transform(matrix);          
}
```
_graph.GeometryGraph.Transform method does not apply the transformation to subgraphs.

**Comment by levnach** [comment]
Sorry, you wrote "proposal could be":-) Did the proposal work for you?

**Comment by patente** [comment]
I changed the above code to reflect the logic of Transform method. So, after the following code in "Transform" method of GeometryGraph.cs:

```
foreach (var node in Nodes)
                node.Transform(matrix);
```

 I just added these lines and it worked:

```
var nodeSet = new Set<Node>(Nodes);
foreach (var cluster in RootCluster.AllClustersDepthFirstExcludingSelf())
{
     foreach (var node in cluster.Nodes.Where(n => !nodeSet.Contains(n)))
     node.Transform(matrix);
     ((Node)cluster).Transform(matrix);
}
```
