### ISSUE TITLE
Video link on the Readme.md no longer valid

### ISSUE THREAD

**Issue by gduncan411** [Microsoft/automatic-graph-layout#89]
In the Readme.md there's a link to a video that is no longer valid.

"This functionality allows viewing a large graph in the online map fashion. Here is a **video** demoing GraphMaps. To see the system in action please open Lg.sln, build it, and run TestGraphMaps. The configuration Release/x64 needs to be used to load..."

The link goes to http://1drv.ms/1IsBEVh which is no longer available

**Comment by mwherman2000** [comment]
It's on YouTube. Search for GraphMap

**Comment by levnach** [comment]
Thank you, the link has been restored. The link on youtube is for the next version that is still in works.
